import { DailyRecord, InBodyRecord, UserSettings, WorkoutCategory } from '../types';

export const initialCategories: WorkoutCategory[] = [
  {
    id: 'cat-1',
    name: '헬스',
    items: ['천국의 계단', '러닝머신', '자전거', '레그프레스', '렛풀다운'],
  },
  {
    id: 'cat-2',
    name: '홈트',
    items: ['스쿼트', '플랭크', '실내자전거', '덤벨 운동', '홈트 영상'],
  },
  {
    id: 'cat-3',
    name: '유산소/야외',
    items: ['인터벌 러닝', '만보 걷기', '등산', '산책'],
  },
  {
    id: 'cat-4',
    name: '필라테스/요가',
    items: ['기구 필라테스', '매트 요가', '폼롤러 스트레칭'],
  },
];

export const initialSettings: UserSettings = {
  targetWeight: 58.0,
  startWeight: 71.39,
  height: 164,
  targetDate: '2026-12-31',
  columns: {
    showWeight: true,
    showWorkout: true,
    showAlcohol: true,
    showPeriod: true,
    showCalories: false,
    showMemo: true,
  },
};

export const initialInBodyRecords: InBodyRecord[] = [
  {
    id: 'inbody-3',
    date: '2026-09-20',
    weight: 67.7,
    skeletalMuscle: 23.6,
    bodyFatPercent: 28.5,
    waistHipRatio: 0.81,
    visceralFatLevel: 6,
    memo: '천국의 계단 열심히 타서 체지방 20%대 진입!',
  },
  {
    id: 'inbody-1',
    date: '2026-07-20',
    weight: 71.5,
    skeletalMuscle: 22.8,
    bodyFatPercent: 33.2,
    waistHipRatio: 0.86,
    visceralFatLevel: 8,
    memo: '다이어트 시작 인바디 측정',
  },
];

// 스크린샷 1과 2에 등장하는 실제 체중 및 활동 데이터
export const initialRecords: DailyRecord[] = [
  // 2026년 9월
  {
    id: 'rec-2026-09-21',
    date: '2026-09-21',
    weight: 67.7,
    workoutDone: true,
    workoutCategory: '헬스',
    workoutType: '천국의 계단',
    workoutDuration: 40,
    workoutCalories: 320,
    period: false,
    alcoholCount: 0,
    memo: '143',
  },
  {
    id: 'rec-2026-09-20',
    date: '2026-09-20',
    weight: null,
    workoutDone: false,
    period: false,
    alcoholCount: 0,
    memo: '',
  },
  {
    id: 'rec-2026-09-19',
    date: '2026-09-19',
    weight: 68.2,
    workoutDone: false,
    period: false,
    alcoholCount: 0,
    memo: '',
  },
  {
    id: 'rec-2026-09-18',
    date: '2026-09-18',
    weight: 68.2,
    workoutDone: false,
    period: false,
    alcoholCount: 0,
    memo: '',
  },
  {
    id: 'rec-2026-09-17',
    date: '2026-09-17',
    weight: null,
    workoutDone: false,
    period: false,
    alcoholCount: 0,
    memo: '',
  },
  {
    id: 'rec-2026-09-16',
    date: '2026-09-16',
    weight: null,
    workoutDone: false,
    period: true,
    alcoholCount: 0,
    memo: '생리',
  },
  {
    id: 'rec-2026-09-15',
    date: '2026-09-15',
    weight: null,
    workoutDone: false,
    period: true,
    alcoholCount: 0,
    memo: '',
  },
  {
    id: 'rec-2026-09-14',
    date: '2026-09-14',
    weight: null,
    workoutDone: false,
    period: false,
    alcoholCount: 0,
    memo: '',
  },
  {
    id: 'rec-2026-09-13',
    date: '2026-09-13',
    weight: null,
    workoutDone: false,
    period: false,
    alcoholCount: 0,
    memo: '',
  },
  {
    id: 'rec-2026-09-12',
    date: '2026-09-12',
    weight: 69.8,
    workoutDone: true,
    workoutCategory: '헬스',
    workoutType: '러닝머신',
    workoutDuration: 45,
    workoutCalories: 280,
    period: false,
    alcoholCount: 0,
    memo: '',
  },
  {
    id: 'rec-2026-09-11',
    date: '2026-09-11',
    weight: null,
    workoutDone: false,
    period: false,
    alcoholCount: 0,
    memo: '',
  },
  {
    id: 'rec-2026-09-05',
    date: '2026-09-05',
    weight: 69.5,
    workoutDone: false,
    period: false,
    alcoholCount: 0,
    memo: '',
  },

  // 2026년 7월 데이터
  {
    id: 'rec-2026-07-25',
    date: '2026-07-25',
    weight: 71.39,
    workoutDone: true,
    workoutCategory: '헬스',
    workoutType: '천국의 계단',
    period: false,
    alcoholCount: 3,
    memo: '시작 몸무게 측정',
  },
];
